name: chat_app_study
description: A new Flutter project.




version: 1.0.0+1

environment:
  sdk: '>=2.19.0-273.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  google_sign_in: ^5.4.2
  provider: ^6.0.4
  flutter_signin_button: ^2.0.0
  google_fonts: ^3.0.1
  firebase_messaging: ^14.1.1
  firebase_storage: ^11.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  assets:
    - images/user.png