// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiIYG-pdOdHUJKcbIQk4VoIMbqrLikLhw',
    appId: '1:924671912627:web:87937f0481b6a0fdd31ec6',
    messagingSenderId: '924671912627',
    projectId: 'chat-test-study',
    authDomain: 'chat-test-study.firebaseapp.com',
    storageBucket: 'chat-test-study.appspot.com',
    measurementId: 'G-T0T51F1E9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiIeBKDP1Oq-5L0S-EDtfN3RHu1lYLdxU',
    appId: '1:924671912627:android:24f2f618684a1f7ad31ec6',
    messagingSenderId: '924671912627',
    projectId: 'chat-test-study',
    storageBucket: 'chat-test-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS7392OkBloNJwpkrk53VqDileY-Wy3Oc',
    appId: '1:924671912627:ios:d9c0557db41c6354d31ec6',
    messagingSenderId: '924671912627',
    projectId: 'chat-test-study',
    storageBucket: 'chat-test-study.appspot.com',
    iosClientId: '924671912627-1dv7bq6vgcj3dnpb34vlsetdbntuihjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppStudy',
  );
}
